version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000' # Mapeia a porta 3000 do container para a 3000 do host
    environment:
      DATABASE_URL: mysql://root:2002@db:3306/shoplink
    depends_on:
      - db
    command: >
      sh -c "npx prisma migrate deploy &&
             npm run start:production"

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 2002
      MYSQL_DATABASE: shoplink
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306' # Exponha essa porta se quiser acessar o MySQL do seu host

volumes:
  db_data:
